# role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-viewer-rolebinding
  namespace: default #授權的名稱空間為 default
subjects:
  - kind: User
    name: pod-viewer # 繫結 pod-viewer 使用者
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-viewer # 繫結 Role
  apiGroup: rbac.authorization.k8s.io
