# limit-range-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: limit-range-pod
spec:
  containers:
    - name: default-limit-range-pod
      image: nginx
      resources:
        limits:
          cpu: "1"
          memory: 700Mi
        requests:
          cpu: "1"
          memory: 700Mi